name: Build and test
run-name: ${{ github.actor }} is building and testing shopping list
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: mvn clean install
      - run: mvn verify
      - run: mvn jacoco:report